-- Split MIP/SOD/SOM/SOL into in-progress and completed statuses.
CREATE TYPE "SoulStage_new" AS ENUM (
  'FIRST_TIMER',
  'FOLLOW_UP',
  'MIP_IN_PROGRESS',
  'MIP_COMPLETED',
  'SOD_IN_PROGRESS',
  'SOD_COMPLETED',
  'SOM_IN_PROGRESS',
  'SOM_COMPLETED',
  'SOL_IN_PROGRESS',
  'SOL_COMPLETED'
);

ALTER TABLE "SoulTracker" ALTER COLUMN "currentStage" DROP DEFAULT;

ALTER TABLE "SoulTracker"
  ALTER COLUMN "currentStage" TYPE "SoulStage_new"
  USING (
    CASE "currentStage"::text
      WHEN 'FIRST_TIMER' THEN 'FIRST_TIMER'
      WHEN 'FOLLOW_UP' THEN 'FOLLOW_UP'
      WHEN 'MIP' THEN 'MIP_IN_PROGRESS'
      WHEN 'MIP_IN_PROGRESS' THEN 'MIP_IN_PROGRESS'
      WHEN 'MIP_COMPLETED' THEN 'MIP_COMPLETED'
      WHEN 'SOD' THEN 'SOD_IN_PROGRESS'
      WHEN 'SOD_IN_PROGRESS' THEN 'SOD_IN_PROGRESS'
      WHEN 'SOD_COMPLETED' THEN 'SOD_COMPLETED'
      WHEN 'SOM' THEN 'SOM_IN_PROGRESS'
      WHEN 'SOM_IN_PROGRESS' THEN 'SOM_IN_PROGRESS'
      WHEN 'SOM_COMPLETED' THEN 'SOM_COMPLETED'
      WHEN 'SOL' THEN 'SOL_IN_PROGRESS'
      WHEN 'SOL_IN_PROGRESS' THEN 'SOL_IN_PROGRESS'
      WHEN 'SOL_COMPLETED' THEN 'SOL_COMPLETED'
      ELSE 'FOLLOW_UP'
    END
  )::"SoulStage_new";

ALTER TABLE "SoulStageEvent"
  ALTER COLUMN "stage" TYPE "SoulStage_new"
  USING (
    CASE "stage"::text
      WHEN 'FIRST_TIMER' THEN 'FIRST_TIMER'
      WHEN 'FOLLOW_UP' THEN 'FOLLOW_UP'
      WHEN 'MIP' THEN 'MIP_IN_PROGRESS'
      WHEN 'MIP_IN_PROGRESS' THEN 'MIP_IN_PROGRESS'
      WHEN 'MIP_COMPLETED' THEN 'MIP_COMPLETED'
      WHEN 'SOD' THEN 'SOD_IN_PROGRESS'
      WHEN 'SOD_IN_PROGRESS' THEN 'SOD_IN_PROGRESS'
      WHEN 'SOD_COMPLETED' THEN 'SOD_COMPLETED'
      WHEN 'SOM' THEN 'SOM_IN_PROGRESS'
      WHEN 'SOM_IN_PROGRESS' THEN 'SOM_IN_PROGRESS'
      WHEN 'SOM_COMPLETED' THEN 'SOM_COMPLETED'
      WHEN 'SOL' THEN 'SOL_IN_PROGRESS'
      WHEN 'SOL_IN_PROGRESS' THEN 'SOL_IN_PROGRESS'
      WHEN 'SOL_COMPLETED' THEN 'SOL_COMPLETED'
      ELSE 'FOLLOW_UP'
    END
  )::"SoulStage_new";

DROP TYPE "SoulStage";
ALTER TYPE "SoulStage_new" RENAME TO "SoulStage";

ALTER TABLE "SoulTracker"
  ALTER COLUMN "currentStage" SET DEFAULT 'FIRST_TIMER'::"SoulStage";
