packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  "@prisma/client": true
  prisma: true
  "@prisma/engines": true
  esbuild: true

minimumReleaseAgeExclude:
  - default-browser
  - electron-to-chromium
  - es-toolkit
